-- AIRAG Metrics Dashboard V2 (Active Pipeline)
-- These queries calculate the required P1/P2 operational metrics using the active `generation_runs` table.

-- 1. Pipeline Success & Adaptive Utilization
SELECT 
    COUNT(*) as total_runs,
    SUM(CASE WHEN status = 'COMPLETED' THEN 1 ELSE 0 END) as successful_runs,
    ROUND(SUM(CASE WHEN status = 'COMPLETED' THEN 1 ELSE 0 END)::numeric / COUNT(*) * 100, 2) as success_rate_pct,
    SUM(CASE WHEN is_adaptive = TRUE THEN 1 ELSE 0 END) as adaptive_runs,
    ROUND(SUM(CASE WHEN is_adaptive = TRUE THEN 1 ELSE 0 END)::numeric / COUNT(*) * 100, 2) as adaptive_utilization_pct
FROM public.generation_runs;

-- 2. AI Automated Catch Rate (Critic Efficiency)
-- Shows how many hallucinated or low-quality questions the AI caught and threw away before saving.
SELECT 
    SUM(raw_generated) as total_candidates_generated,
    SUM(validated_count) as total_passed_critic,
    SUM(raw_generated - validated_count) as total_caught_by_system,
    ROUND(SUM(raw_generated - validated_count)::numeric / NULLIF(SUM(raw_generated), 0) * 100, 2) as automated_catch_rate_pct
FROM public.generation_runs
WHERE status = 'COMPLETED';

-- 3. Surplus Pool Health (Are we fulfilling professor requests?)
-- Compares what the professor originally requested vs what was actually saved to their quiz pool.
SELECT 
    request_id,
    created_at,
    requested_count,
    target_pool_size,
    raw_generated,
    saved_count,
    (saved_count - requested_count) as surplus_questions_generated
FROM public.generation_runs
WHERE status = 'COMPLETED'
ORDER BY created_at DESC
LIMIT 10;

-- 4. Question Difficulty Distribution
-- Shows the distribution of Easy/Medium/Hard questions generated by the adaptive AI.
SELECT 
    difficulty,
    COUNT(*) as total_generated,
    ROUND(COUNT(*)::numeric / SUM(COUNT(*)) OVER() * 100, 2) as distribution_pct
FROM public."GeneratedQuestion"
GROUP BY difficulty
ORDER BY total_generated DESC;

-- 5. Bloom's Taxonomy Cognitive Level Breakdown
SELECT 
    "bloomLevel",
    COUNT(*) as count,
    ROUND(COUNT(*)::numeric / SUM(COUNT(*)) OVER() * 100, 2) as percentage
FROM public."GeneratedQuestion"
GROUP BY "bloomLevel"
ORDER BY count DESC;

